### ISSUE TITLE
Entrega

### ISSUE THREAD

**Issue by florenciarimolo** [florenciarimolo/asw_api#1]
- ~Vote/Unvote, Watch/Unwatch @DuveD~
- ~Api-token @florenciarimolo~
- ~CORS headers @jessicasobreviela~ 
- ~Attachment @jonator8~
- ~Notación HAL @jessicasobreviela~ 
- ~Añadir los created_at y updated_at como atributos en las issues y comentarios @DuveD~
- ~Añadir el usuario que ha creado la issue como campo @florenciarimolo~
- ~Añadir el usuario que ha creado el comentario como campo @florenciarimolo~
- ~Filtros de issues @jonator8~
- ~Swagger~

**Comment by florenciarimolo** [comment]
~También falta el Readme.~

**Comment by DuveD** [comment]
Swagger actualizado con comentarios. Falta actualizar la view que lo muestra.

**Comment by florenciarimolo** [comment]
Añadir la url de Heroku en el README.
