### ISSUE TITLE
Allow all methods?

### ISSUE THREAD

**Issue by florenciarimolo** [florenciarimolo/asw_api#2]
Preguntarle al profe si nuestra API permite todos los methods (GET, POST,PUT, PATCH, DELETE, HEAD, OPTIONS) o sólo GET, POST, PUT, DELETE

**Comment by carlesf** [comment]
Només cal GET, POST, PUT, DELETE, però l'OPTIONS també el necessitareu per al CORS.

**Comment by florenciarimolo** [comment]
Ok, gràcies!
